### ISSUE TITLE
Ruby on Rails dev - 800-2500USD (Saigon), 3700-5000 SGD (Singapore, EP sponsor) at Ring.MD

### ISSUE THREAD

**Issue by longkt90** [HCMUS-IT/job_board#166]
RingMD is a young startup with a small team of less than 10 people and we inspire each other to innovate and provide the best service in Healthcare. We are currently seeking candidates to join our team full time as a Web developer. 
# Job Description:
- Join Ruby on Rails developers team to build web app and APIs for our product, Ring.MD
- Work initially in Ho Chi Minh and move to Singapore after two months (Singaporean salary, Employment Pass sponsor).
- Do research on technology that can benefit the app.
- Code review and design discussion with teammates.
# What we’re looking for

1/ Are you bright, not just smart?

We’re looking for generalists. That doesn’t mean that you already know everything; it means that you’re both willing and able to learn new things quickly. We’re looking for conceptual thinkers. Can you think about problems at a high level and then solve them in code with a constant focus on the higher-level problem you’re solving?

2/ Do you fit?

Culture is critically important here. Not only do we need people who can work well in small teams, we also want to make sure that our values mesh. We believe in collaboration across the entire company, taking responsibility to make things work, and delivering a product which delights our users.
## Must have:
- 2+ years experience writing web applications using Ruby, RoR
- Experience with MySQL/PostgreSQL
- Be able to communicate and or at least to write in English
- Solid understand about TCP/IP, RESTful, test automation
- Experience in JavaScript, AngularJs, jQuery, and frontend dev
- Git experience
## Ideally
- Experience architecting large scale Ruby/Rails applications
- Knowledge/experience with redis, memcached
- Experience building responsive web applications
- An active participation of open source projects
# Why work at RingMD?

By joining the team as a developer, you’ll be an intricate part of working on product that will have massive impact on millions of users. Your voice will be heard and you’ll have a lot of autonomy over mission-critical decisions. We make healthcare more convenient and affordable.
## Benefit:
- High and competitive salary, 800-2500USD/month working in Saigon, 3700-5000 SGD/month working in Singapore.
- Young and proactive working environment
- You have more control and flexibility
# Contact us
- Please send your CV to long(at)ring.md

**Comment by oItachi** [comment]
cool
