### ISSUE TITLE
ATADI tuyển dụng

### ISSUE THREAD

**Issue by Chickyky** [HCMUS-IT/job_board#208]
Thông tin tuyển dụng từ atadi.vn
atadi.vn là website đầu tiên tại Việt Nam giúp người dùng tìm kiếm, so sánh và săn vé máy bay khuyến mãi trực tuyến của tất cả các hãng hàng không.
Để ngày càng hoàn thiện hơn về mặt chất lượng và tiếp tục mở rộng nhiều tính năng tiện ích nhằm phục vụ người dùng trong lĩnh vực hàng không và du lịch trong năm 2015, atadi.vn thông báo tuyển cộng tác viên cho hệ thống ở các vị trí dưới bên dưới:
1. Đội ngũ kỹ thuật
   Mô tả công việc:
2. Thiết kế và phát triển Web bằng ngôn ngữ PHP/NodeJS
3. Thiết kế và phát triển Web bằng ngôn ngữ sử dụng jQuery, HTML5/CSS3, AngularJS, Object DB (Mongo/Redis), Relational DB (mySQL)
4. Thiết kế và phát triển hệ thống cơ sở hạ tầng sử dụng điện toán đám mây Google/Amazon/Azure
   Quyền lợi:
5. Môi trường làm việc hiện đại với các chuyên gia hàng đầu trong lĩnh vực công nghệ web và điện toán đám mây mới nhất
6. Có nhiều cơ hội sáng tạo, thể hiện khả năng của bản thân, học hỏi, phát triển kỹ năng và kinh nghiệm.
7. Tạo điều kiện nghiên cứu và phát triển công nghệ
   Yêu cầu công việc
8. Kiến thức nền tảng vững chắc về nguyên lý lập trình web, nguyên lý hoạt động của các website
9. Không cần kinh nghiệm nhưng phải có tư duy logic tốt
10. Ham học hỏi và tiếp cận công nghệ mới

Số lượng: 06
1. Đội ngũ thiết kế
   Mô tả công việc:
2. Thiết kế và phát triển giao diện web thân thiện với end-user
3. Thiết kế web theo yêu cầu, theo file pds

Yêu cầu công việc
- Có gu thẩm mỹ tốt.
- Biết sử dụng Photoshop, Corel
- Có thể sử dụng Framework Bootstrap
- Hiểu biết về HTML, CSS, jquery, javascript
- Biết SEO là một lợi thế

Số lượng: 03
1. Cộng tác viên xây dựng nội dung Blog và Facebook
   Mô tả công việc:
2. Tìm kiếm, chia sẻ và dịch các nguồn thông tin về hàng không và du lịch
3. Tổ chức các sự kiện trên Facebook để tăng cường tương tác và thu thập thông tin tới các nhóm khách hàng
   Yêu cầu công việc
4. Có kinh nghiệm hoạt động và tham gia hoạt động mạng xã hội và diễn đàn
5. Yêu thích du lịch
6. Năng động, sáng tạo

Số lượng: 05
1. Đội ngũ Help Desk (hỗ trợ khách hàng) và Call Center (tổng đài)
   Mô tả công việc:
2. Trả lời những câu hỏi, thắc mắc và hỗ trợ khách hàng trong quy trình đặt và thanh toán vé
3. Tư vấn và giải đáp các dịch vụ hàng không, du lịch
4. Tư vấn và giải đáp các dịch vụ thanh toán Internet Banking, chuyển khoản
   Yêu cầu công việc
5. Có kinh nghiệm đặt và thanh toán vé máy bay trực tuyến
6. Từng tham gia các ngành nghề liên quan là 1 thế mạnh

Số lượng: 05

Môi trường làm việc:
- Địa chỉ văn phòng atadi.vn: 50A Nguyễn Thái Sơn, F.3 Q.Gò Vấp, Tp.HCM
- Link bản đồ: https://goo.gl/mZ5RcM
- Trong thời gian sắp tới atadi sẽ mở rộng ra 1 số văn phòng làm việc tại khu vực quận Phú Nhuận, Tân Bình, Bình Thạnh
- Thời gian làm việc: 8h - 6h 
- Lương thỏa thuận theo năng lực và thời gian cộng tác

Thông tin liên lạc:
Gửi hồ sơ tuyển dụng qua địa chỉ email: hr@atadi.vn

**Comment by ngnguyen1** [comment]
Website sử dụng Node.js. Ngon đấy. :+1:

**Comment by Chickyky** [comment]
:D
