### ISSUE TITLE
Làm trang quản lý trang login dùng PHP

### ISSUE THREAD

**Issue by binhtv** [HCMUS-IT/job_board#283]
Mình cần 1 bạn làm PHP để làm tool quản lý trang đăng nhập, cho chọn template, chọn hình background, chọn logo. HTML đã có sẵn.
Admin sẽ vào tool quản lý customize chọn template( những template này mình sẽ cung cấp HTML), logo, header, footer để tạo ra 1 trang login hoàn chỉnh
Yêu cầu chuyên môn:
1/ Biết lập trình ngôn ngữ PHP
2/ Sử dụng thành thạo HTML, CSS, Javascript
3/ Ưu tiên biết FW Laravel

Giá cả: 3 triệu đồng

Bạn nào quan tâm thì liên hệ với mình binh12121989@gmail.com để bàn chi tiết hơn nhé!

**Comment by dangkaka** [comment]
có thể nói kĩ chút xíu ko bạn ơi, mình có hứng thú nè :+1:
