### ISSUE TITLE
[URGENT] Cần tuyển nhân viên Part-time/Freelancer (NodeBB, NodeJS)

### ISSUE THREAD

**Issue by hoabang** [HCMUS-IT/job_board#593]
Công ty TNHH Giải Pháp Công Nghệ DCT cần tuyển 1 nhân viên Freelancer/part-time thực hiện 1 project ngắn hạn trong vòng 3 tháng (1 tháng thực hiện + 2 tháng bảo trì nếu có vấn đề). 

Yêu cầu kinh nghiệm: 
- Có kinh nghiệm làm việc với NodeBB (từ 6 tháng trở lên)
- Am hiểu về NodeJS, HTML, CSS

Thời gian làm việc: Thỏa thuận (đảm bảo hiệu quả công việc để launch sản phẩm vào ngày 08.01.2016)
Budget cho gói 3 tháng: 5.000.000 VND

CV ứng tuyển xin gửi về: bangvuquynhhoa@gmail.com 
Mọi chi tiết xin liên hệ email: bangvuquynhhoa@gmail.com hoặc số điện thoại O122 793 658O để trao đổi trực tiếp.
Xin chân thành cảm ơn.

**Comment by longkt90** [comment]
Position filled
